### PR TITLE
WIP: Auto Fishing

### PR DESCRIPTION
**Pull request by ProphetRTE**
# Implemented Auto Fishing!!

# Credit to [Click](https://github.com/CIick) for the bot I'm implementing. and a big thanks for helping me out!

## Known code issues:
- refresh_pond in auto_fish.py cannot be awaited or it will immediately stop the auto fishing. if it's not awaited you get an error that you need to await it, but the fishing still works. I've commented it for now. feel free to work on it and improve that.
- The fish_id and is_fish_chest settings don't work because I can't await refresh_pond so when that get's fixed so does the settings. For now it's just fishes nothing specific.

Toggle Key is F10 by default. 

This is for more clarity 

# Specifications
is_fish_chest = False   # Fish for Chests only                                 
fish_school = "Any" # "Any" means you don't care                      
fish_rank = 0  # 0 means you don't care                                       
fish_id = 0 # 0 means you don't care    (Fish for a specified fish)                                     
min_fish_size = 0 # 0 means you don't care                                 
max_fish_size = 999 # big number means you don't care

# Fish IDs
Some might be missing.
[Fish_IDs.json](https://github.com/user-attachments/files/16569907/Fish_IDs.json)

### CODE REVIEW

**Comment by bilibilizhiyicn** [comment]
You'll do it!

**Comment by bilibilizhiyicn** [comment]
I tried it and it was pretty crazy

**Comment by bilibilizhiyicn** [comment]
And then I want to ask, what is this for? is_fish_chest and fish_id

**Comment by SirOlaf** [comment]
Biggest issue with adding this is that someone has to maintain the patterns if they break, also probably gonna get patched quickly if it's easy to use. But I said before I'm not gonna stop anyone from adding it, so good luck getting those bugs fixed.

**Comment by SirOlaf** [comment]
Should probably also credit major (or maybe faj? Not sure who made the bot you copy and pasted.)
Don't need to credit me for the offsets that get patched, they didn't credit me either for that.

**Comment by bilibilizhiyicn** [comment]
So isn't this a Wizwalker-based feature?

**Comment by bilibilizhiyicn** [comment]
So this feature may be fixed later？

**Comment by bilibilizhiyicn** [comment]
is_fish_chest = False or True I tried and couldn't fish for chests only

**Comment by bilibilizhiyicn** [comment]
You're using wizwalker to rely on the functionality in the library, right? I looked at the code, and if he was fixed, wizWalker would probably try to fix it, too?

**Pull request closed without merging**
